name: Version handler
author: Nick Marshall
description: Confirms changes in known package.
branding:
  color: blue
  icon: chevron-up
inputs:
  repoTag:
    description: "Tag used for repository name."
    required: false
    default: ""
  versionsDir:
    description: "Directory containing tags/pkg versions"
    required: false
    default: "version"
  pkg:
    description: "Directory of package that we're checking"
    required: false
    default: ""
  pkgRef:
    description: "Speed up the process by suppling the packages HEAD ref."
    required: false
    default: ""
  # ghRepo:
  #   description: "Working repo - This repo."
  #   required: false
  #   default: $GITHUB_REPOSITORY
  # ghToken:
  #   description: "Github token needed to sync repo."
  #   required: false
  #   default: ${{ secrets.GITHUB_TOKEN }}
tputs:
  updatePkg:
    description: "Whether or not package should be rebuilt."
runs:
  using: 'docker'
  image: 'Dockerfile'   